# Generated by Django 4.2.7 on 2023-11-19 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bookmark", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="id",
        ),
        migrations.RemoveField(
            model_name="challengebookmark",
            name="id",
        ),
        migrations.RemoveField(
            model_name="lab",
            name="id",
        ),
        migrations.RemoveField(
            model_name="labbookmark",
            name="id",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengebookmark",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lab",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="labbookmark",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
