# Generated by Django 4.2.7 on 2023-11-19 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmark", "0002_remove_challenge_id_remove_challengebookmark_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengebookmark",
            name="title",
        ),
        migrations.RemoveField(
            model_name="labbookmark",
            name="title",
        ),
    ]
